name: Add TMDB Object

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: "TMDB Object Type"
        required: true
        default: "people"
        options:
          - people
          - companies
      id:
        description: "TMDB Object ID"
        required: true

permissions:
  contents: write

jobs:
  add:
    runs-on: ubuntu-24.04
    concurrency: git-push-data

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v5

      - name: Append data
        run: |
          echo "$ID" >>"$FILENAME"
          sort -t '-' -k1,1n -u "$FILENAME" -o "$FILENAME"
        env:
          ID: ${{ github.event.inputs.id }}
          FILENAME: ${{ github.event.inputs.type }}.csv

      - name: Commit changes
        id: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./*.csv
          if git commit --message "Add TMDB ${{ github.event.inputs.type }}"; then
              echo "committed=true" >>"$GITHUB_OUTPUT"
          else
              echo "committed=false" >>"$GITHUB_OUTPUT"
          fi

      - name: Push changes
        if: steps.commit.outputs.committed == 'true'
        run: git push
